"""update relations

Revision ID: 0071ca4660c9
Revises: 10dde5617668
Create Date: 2024-01-01 16:44:36.011721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0071ca4660c9'
down_revision: Union[str, None] = '10dde5617668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'created_by_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'created_by_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
