"""update table token

Revision ID: fa153243478b
Revises: 0071ca4660c9
Create Date: 2024-01-01 17:25:15.453441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa153243478b'
down_revision: Union[str, None] = '0071ca4660c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.drop_column('tokens', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('created_date', mysql.DATETIME(), nullable=True))
    op.drop_column('tokens', 'expires_at')
    # ### end Alembic commands ###
